import type { Quiz } from '../../types/quiz';

export const howTsunamisFormQuiz: Quiz = {
  id: 'quiz-how-tsunamis-form',
  experienceSlug: 'how-tsunamis-form',
  title: 'Tsunami Physics & Genesis Verification Quiz',
  description: 'Evaluate your understanding of megathrust seafloor displacement, open-ocean vs shoaling wave dynamics, and the 2004 Aceh disaster.',
  passingScore: 70,
  questions: [
    {
      id: 'q1-genesis-cause',
      type: 'single-choice',
      prompt: 'What physical event most commonly generates destructive, trans-oceanic tsunami waves?',
      contextNarrative: 'Consider what tectonic action displaces the greatest volume of the overlying ocean column.',
      options: [
        {
          id: 'opt-high-winds',
          label: 'Strong tropical storm winds and monsoon typhoons.',
        },
        {
          id: 'opt-vertical-seafloor',
          label: 'Sudden, large-scale vertical displacement of the seafloor during an undersea subduction megathrust earthquake.',
          isCorrect: true,
        },
        {
          id: 'opt-tidal-pull',
          label: 'Gravitational alignment of the moon during lunar eclipses.',
        },
        {
          id: 'opt-whale-pods',
          label: 'Mass movement of marine mammals along continental shelves.',
        },
      ],
      correctAnswer: 'opt-vertical-seafloor',
      explanation: 'Undersea megathrust earthquakes suddenly uplift or drop large areas of the seafloor (e.g., ~15 m of vertical slip over 1,200 km in 2004). This instantly displaces the entire water column above, launching tsunami waves radiating in all directions.',
      relatedConceptSlug: 'subduction',
    },
    {
      id: 'q2-deep-ocean-danger',
      type: 'true-false',
      prompt: 'Tsunami waves are tall and at their most destructive when traveling across the deep open ocean (depth > 3,000 meters).',
      contextNarrative: 'Recall how wave height and wavelength change from deep water to shallow coastal shoaling zones.',
      options: [
        {
          id: 'opt-true',
          label: 'True — open-ocean tsunamis are towering walls of water that easily capsize ships.',
        },
        {
          id: 'opt-false',
          label: 'False — in deep ocean, tsunamis have low amplitudes (< 1 meter) and long wavelengths (100–200 km); destructive shoaling only happens in shallow coastal waters.',
          isCorrect: true,
        },
      ],
      correctAnswer: 'opt-false',
      explanation: 'In deep water, a tsunami wave has an amplitude of less than 1 meter spread across a hundred kilometers of wavelength, making it virtually imperceptible to ships. Only when entering shallow water does wave speed drop, compressing the wavelength and forcing the wave height to surge dramatically (shoaling).',
      relatedConceptSlug: 'subduction',
    },
    {
      id: 'q3-aceh-vs-palu-contrast',
      type: 'single-choice',
      prompt: 'How did the tsunami generation mechanism in the 2018 Palu earthquake differ from the 2004 Sumatra-Andaman event?',
      contextNarrative: 'Recall the contrast between direct vertical megathrust displacement versus indirect strike-slip coastal collapse.',
      options: [
        {
          id: 'opt-identical',
          label: 'Both events were caused by identical open-ocean megathrust fault ruptures.',
        },
        {
          id: 'opt-palu-indirect',
          label: 'Aceh 2004 was generated by direct vertical megathrust seafloor uplift, whereas Palu 2018 was triggered by violent strike-slip shaking inducing secondary submarine landslides and coastal liquefaction collapses in Palu Bay.',
          isCorrect: true,
        },
        {
          id: 'opt-asteroid',
          label: 'Palu 2018 was caused by an asteroid impact in the bay.',
        },
        {
          id: 'opt-dam-burst',
          label: 'Aceh 2004 was caused by an artificial river dam failure.',
        },
      ],
      correctAnswer: 'opt-palu-indirect',
      explanation: 'The 2004 Aceh disaster was a classic primary megathrust vertical seafloor displacement (Mw 9.1–9.3). Palu 2018 occurred on a horizontal strike-slip fault (Mw 7.5), where extreme shaking triggered catastrophic secondary submarine landslides within the confined bay.',
      relatedConceptSlug: 'subduction',
    },
  ],
};
